name: Update Hearthstone Leaderboard

on:
  schedule:
    - cron: '*/20 * * * *'  # 15분마다 실행
  workflow_dispatch:        # 원할 때 버튼을 눌러 수동으로 실행

jobs:
  update-db:
    runs-on: ubuntu-latest  # 깃허브가 제공하는 무료 우분투 서버를 잠시 빌려 씁니다.

    steps:
    - name: 저장소 코드 가져오기
      uses: actions/checkout@v3

    - name: 파이썬 설치하기
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 필요한 라이브러리 설치하기
      run: pip install -r requirements.txt

    - name: 파이썬 스크립트 실행하기
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: python main.py
